// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuyZJHmjsSboIHGTWz6_gdPL3s1LF4UA',
    appId: '1:138292356068:web:04566bea88d21ce3241df1',
    messagingSenderId: '138292356068',
    projectId: 'my-first-f7dff',
    authDomain: 'my-first-f7dff.firebaseapp.com',
    storageBucket: 'my-first-f7dff.appspot.com',
    measurementId: 'G-XWJLV4WLM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoGWG96AmqFHDw9NnnEulrSETWwxZjEE8',
    appId: '1:138292356068:android:34fde0bd44e7190f241df1',
    messagingSenderId: '138292356068',
    projectId: 'my-first-f7dff',
    storageBucket: 'my-first-f7dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcx-cZvgfvLCQlD7BsG_4fSIuJ2kq5YiA',
    appId: '1:138292356068:ios:fe4858d073f3bcec241df1',
    messagingSenderId: '138292356068',
    projectId: 'my-first-f7dff',
    storageBucket: 'my-first-f7dff.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcx-cZvgfvLCQlD7BsG_4fSIuJ2kq5YiA',
    appId: '1:138292356068:ios:fe4858d073f3bcec241df1',
    messagingSenderId: '138292356068',
    projectId: 'my-first-f7dff',
    storageBucket: 'my-first-f7dff.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHuyZJHmjsSboIHGTWz6_gdPL3s1LF4UA',
    appId: '1:138292356068:web:f44c7f53bcd795c8241df1',
    messagingSenderId: '138292356068',
    projectId: 'my-first-f7dff',
    authDomain: 'my-first-f7dff.firebaseapp.com',
    storageBucket: 'my-first-f7dff.appspot.com',
    measurementId: 'G-J8ZBG9SWNQ',
  );
}
